backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections:
  - name: "work"
    label: "Work"
    folder: "_data/_work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Priority",
          name: "priority",
          widget: "number",
          default: 0,
          min: 0,
          max: 100,
          step: 1,
        }
      - { label: "Vimeo Permalink", name: "permalink", widget: "string" }
      - {
          label: "Tag",
          name: "tag",
          widget: "select",
          options:
            ["advertisement", "corporate", "profile-documentary", "reel"],
        }
      - {
          label: "Thumbnail Image",
          name: "thumbnailImage",
          description: "must be 480x360",
          widget: "image",
          default: "/assets/img/uploads/default-thumbnail.jpg",
        }
  - label: "Content"
    name: "content"
    files:
      - label: "Content"
        name: "content"
        file: "_data/content.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - {
              label: "Background Image SlideShow 1",
              name: "bgSlideImage1",
              widget: "image",
            }
          - {
              label: "Background Image SlideShow 2",
              name: "bgSlideImage2",
              widget: "image",
            }
          - {
              label: "Background Image SlideShow 3",
              name: "bgSlideImage3",
              widget: "image",
            }
          - {
              label: "Background Image MOBILE",
              name: "bgMobile",
              widget: "image",
            }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "Featured Title", name: "featuredTitle", widget: "string" }
          - { label: "Featured Text", name: "featuredText", widget: "string" }
          - { label: "Featured Url", name: "featuredUrl", widget: "string" }
          - { label: "Our Projects", name: ourProjects, widget: markdown }
          - {
              label: "Our Project Image",
              name: "ourProjectsImage",
              widget: "image",
            }
          - { label: "Our Projects", name: ourProjectsUrl, widget: string }
          - { label: "Our Projects", name: ourProjectsText, widget: string }
          - {
              label: Sustainable Building,
              name: sustainableBuilding,
              widget: markdown,
            }
          - { label: "Collage Image 1", name: "collage1", widget: "image" }
          - {
              label: "Collage Image 1 Caption",
              name: collage1text,
              widget: string,
            }
          - { label: "Collage Image 1 URL", name: collage1url, widget: string }
          - { label: "Collage Image 2", name: "collage2", widget: "image" }
          - {
              label: "Collage Image 2 Caption",
              name: collage2text,
              widget: string,
            }
          - { label: "Collage Image 2 URL", name: collage2url, widget: string }
          - { label: "Collage Image 3", name: "collage3", widget: "image" }
          - {
              label: "Collage Image 3 Caption",
              name: collage3text,
              widget: string,
            }
          - { label: "Collage Image 3 URL", name: collage3url, widget: string }
          - {
              label: "Sustainable Image",
              name: "sustainableImage",
              widget: "image",
            }
          - {
              label: "Sustainable Url",
              name: "sustainableUrl",
              widget: "string",
            }
          - {
              label: "Sustainable Text",
              name: "sustainableText",
              widget: "string",
            }
          - { label: "Wide Image", name: "wideImage", widget: "image" }
          - {
              label: "Wide Image Caption",
              name: "wideImageCaption",
              widget: "string",
            }
          - { label: "Wide Image Url", name: "wideImageUrl", widget: "string" }
          - { label: "Our Process", name: ourProcess, widget: markdown }
          - { label: About Us, name: aboutUs, widget: markdown }
          - {
              label: "Our Process Image 1",
              name: "aboutUsImageCollage1",
              widget: "image",
            }
          - {
              label: "Our Process Image 1 Caption",
              name: aboutUsImage1CollageCaption,
              widget: string,
            }
          - {
              label: "Our Process Image 1 URL",
              name: aboutUsImage1CollageUrl,
              widget: string,
            }
          - {
              label: "Our Process Image 2",
              name: "aboutUsImageCollage2",
              widget: "image",
            }
          - {
              label: "Our Process Image 2 Caption",
              name: aboutUsImage2CollageCaption,
              widget: string,
            }
          - {
              label: "Our Process Image 2 URL",
              name: aboutUsImage2CollageUrl,
              widget: string,
            }
          - {
              label: "Our Process Image 3",
              name: "aboutUsImageCollage3",
              widget: "image",
            }
          - {
              label: "Our Process Image 3 Caption",
              name: aboutUsImage3CollageCaption,
              widget: string,
            }
          - {
              label: "Our Process Image 3 URL",
              name: aboutUsImage3CollageUrl,
              widget: string,
            }
          - {
              label: "About Us Image 1",
              name: "aboutUsImage2",
              widget: "image",
            }
          - {
              label: "About Us Image 1 Caption",
              name: aboutUsImage2Caption,
              widget: string,
            }
          - {
              label: "About Us Image 1 Url",
              name: aboutUsImage2Url,
              widget: string,
            }
          - {
              label: "About Us Image 2",
              name: "aboutUsImage3",
              widget: "image",
            }
          - {
              label: "About Us Image 2 Caption",
              name: aboutUsImage3Caption,
              widget: string,
            }
          - {
              label: "About Us Image 2 Url",
              name: aboutUsImage3Url,
              widget: string,
            }
