# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections:
  # destinations
  - name: "destination" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Destination" # Used in the UI, ie.: "New Post"
    folder: "_data/_destination" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "destination"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", default: "/assets/img/uploads/morocco.jpg"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Places", name: "places", widget: "map", required: false}
      - {label: "Carly's take", name: "carlyTake", widget: "markdown", required: false}
      - {label: "Nico's take", name: "nicoTake", widget: "markdown", required: false}
      - {label: "Gallery", name: "gallery", widget: "image", default: "/uploads/chocolate-dogecoin.jpg" 
        media_library:
          config:
            multiple: true
        }
  - name: "work"
    label: "work"
    folder: "_work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Vimeo Permalink", name: "permalink", widget: "string" }
      - {
          label: "Tag",
          name: "tag",
          widget: "select",
          options:
            ["advertisement", "corporate", "profile-documentary", "reel"],
        }
      - {
          label: "Thumbnail Image",
          name: "thumbnailImage",
          widget: "image",
          default: "/assets/img/uploads/default-thumbnail.jpg",
        }
