backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections:
  - name: "work"
    label: "Work"
    folder: "_data/_work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Priority",
          name: "priority",
          widget: "number",
          default: 0,
          min: 0,
          max: 100,
          step: 1,
        }
      - { label: "Vimeo Permalink", name: "permalink", widget: "string" }
      - {
          label: "Tag",
          name: "tag",
          widget: "select",
          options:
            ["advertisement", "corporate", "profile-documentary", "reel"],
        }
      - {
          label: "Thumbnail Image",
          name: "thumbnailImage",
          widget: "image",
          default: "/assets/img/uploads/default-thumbnail.jpg",
        }
